name: Hello world GH Actions

on:
    push:
        branches: [ main ]
jobs:
    greeting:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - name: Saludo
          run: echo "Hola mundo"
